/// Generated by Flutter GetX Starter on 2021-11-22 13:56

import 'package:day77_getxnavigation/routes/page_route.dart';

import '../pages/page1.dart';
import 'package:flutter/material.dart';
import 'package:get/get_navigation/get_navigation.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: PageSatu(),
      initialRoute: '/',
      getPages: AppPages.pages,
    );
  }
}
